'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IF_SaldoClientesV
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="ipostep_vP.0010000101.in_WCSX_com.sap.b1i.vplatform.runtime_INB_WS_CALL_SYNC_XPT_"& _ 
        "INB_WS_CALL_SYNC_XPT.ipo_proc", [Namespace]:="urn:ipostep_vP.0010000101.in_WCSX_com.sap.b1i.vplatform.runtime_INB_WS_CALL_SYNC_"& _ 
        "XPT_INB_WS_CALL_SYNC_XPT.ipo_proc", ConfigurationName:="IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CA"& _ 
        "LL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc")>  _
    Public Interface ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z.SaldoClientesV no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ZSaldoClientesV(ByVal request As IF_SaldoClientesV.ZSaldoClientesVRequest) As IF_SaldoClientesV.ZSaldoClientesVResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function ZSaldoClientesVAsync(ByVal request As IF_SaldoClientesV.ZSaldoClientesVRequest) As System.Threading.Tasks.Task(Of IF_SaldoClientesV.ZSaldoClientesVResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaldoClientesVType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaldoClientesVResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private saldoClientesVResultField() As SaldoClientesVResponseTypeRow
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Row", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property SaldoClientesVResult() As SaldoClientesVResponseTypeRow()
            Get
                Return Me.saldoClientesVResultField
            End Get
            Set
                Me.saldoClientesVResultField = value
                Me.RaisePropertyChanged("SaldoClientesVResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class SaldoClientesVResponseTypeRow
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cardCodeField As String
        
        Private cardNameField As String
        
        Private balanceField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property CardCode() As String
            Get
                Return Me.cardCodeField
            End Get
            Set
                Me.cardCodeField = value
                Me.RaisePropertyChanged("CardCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property CardName() As String
            Get
                Return Me.cardNameField
            End Get
            Set
                Me.cardNameField = value
                Me.RaisePropertyChanged("CardName")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property Balance() As String
            Get
                Return Me.balanceField
            End Get
            Set
                Me.balanceField = value
                Me.RaisePropertyChanged("Balance")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZSaldoClientesVRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public SaldoClientesV As IF_SaldoClientesV.SaldoClientesVType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SaldoClientesV As IF_SaldoClientesV.SaldoClientesVType)
            MyBase.New
            Me.SaldoClientesV = SaldoClientesV
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZSaldoClientesVResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public SaldoClientesVResponse As IF_SaldoClientesV.SaldoClientesVResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SaldoClientesVResponse As IF_SaldoClientesV.SaldoClientesVResponseType)
            MyBase.New
            Me.SaldoClientesVResponse = SaldoClientesVResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_procChannel
        Inherits IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_procClient
        Inherits System.ServiceModel.ClientBase(Of IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc)
        Implements IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IF_SaldoClientesV_ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc_ZSaldoClientesV(ByVal request As IF_SaldoClientesV.ZSaldoClientesVRequest) As IF_SaldoClientesV.ZSaldoClientesVResponse Implements IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc.ZSaldoClientesV
            Return MyBase.Channel.ZSaldoClientesV(request)
        End Function
        
        Public Function ZSaldoClientesV(ByVal SaldoClientesV As IF_SaldoClientesV.SaldoClientesVType) As IF_SaldoClientesV.SaldoClientesVResponseType
            Dim inValue As IF_SaldoClientesV.ZSaldoClientesVRequest = New IF_SaldoClientesV.ZSaldoClientesVRequest()
            inValue.SaldoClientesV = SaldoClientesV
            Dim retVal As IF_SaldoClientesV.ZSaldoClientesVResponse = CType(Me,IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc).ZSaldoClientesV(inValue)
            Return retVal.SaldoClientesVResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IF_SaldoClientesV_ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc_ZSaldoClientesVAsync(ByVal request As IF_SaldoClientesV.ZSaldoClientesVRequest) As System.Threading.Tasks.Task(Of IF_SaldoClientesV.ZSaldoClientesVResponse) Implements IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc.ZSaldoClientesVAsync
            Return MyBase.Channel.ZSaldoClientesVAsync(request)
        End Function
        
        Public Function ZSaldoClientesVAsync(ByVal SaldoClientesV As IF_SaldoClientesV.SaldoClientesVType) As System.Threading.Tasks.Task(Of IF_SaldoClientesV.ZSaldoClientesVResponse)
            Dim inValue As IF_SaldoClientesV.ZSaldoClientesVRequest = New IF_SaldoClientesV.ZSaldoClientesVRequest()
            inValue.SaldoClientesV = SaldoClientesV
            Return CType(Me,IF_SaldoClientesV.ipostep_vP0010000101in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc).ZSaldoClientesVAsync(inValue)
        End Function
    End Class
End Namespace
